version: "3.3"
services:
    flask:
        build: ./flask/.
        ports:
        - "5000:5000"
    apache2: 
        build: ./apache2/.
        ports:
        - "8080:8080"
    nginx: 
        build: ./nginx/.
        ports:
        - "83:83"
    phpmyadmin: 
        build: ./phpmyadmin/.
        ports:
        - "9090:9090"
    nodejs:
        build: ./nodejs/.
        ports:
        - "81:81"
    php_apache: 
        build: ./php_apache/.
        ports:
        - "82:82"
    